### ISSUE TITLE
Campos que devem ser adicionados no kernel.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/kernel#147]
Verificando a necessidade do OPAC os seguintes campos  não estão contemplados no Kernel: 

```python
    timeline 
    social_networks 
    next_title 
    copyrighter 
    logo_url 
    previous_journal_ref 
    other_titles 
    publisher_name 
    publisher_country 
    publisher_state 
    publisher_city 
    publisher_address 
    publisher_telephone 
    index_at 
    scimago_id 
```

**Comment by jamilatta** [comment]
@gustavofonseca @robertatakenaka @patymori @joffilyfe 

Estou realizando a atividade https://github.com/scieloorg/opac/issues/1453, esta atividade tem como objetivo exibir o nome do publicador no cabeçalho das páginas do site. 

Atualmente não temos no kernel alguns dos campos mencionados nesse ticket, exemplo, para realizar essa atividade todos com o prefixo **publisher**. 

No opac-ariflow estamos utilizando os campos de contato do Kernel para preencher os campos com prefixo **publisher**, vejam: 

![Screenshot 2019-12-03 14 52 18](https://user-images.githubusercontent.com/373745/70075931-849b9a80-15dc-11ea-8087-6e75f9738a69.png)

Estamos armazenando os campos de **contact** como **publisher**, reparem no trecho de código do ariflow: 

![Screenshot 2019-12-03 14 53 41](https://user-images.githubusercontent.com/373745/70076026-b6acfc80-15dc-11ea-8909-93850a30114a.png)

Em vários periódicos o **patrocinador** também é o **publicador**, como por exemplo, o periódico Acta Amazonica (aa), não sendo um regra, portanto não podemos considerar que o campo que estamos armazenando no kernel como **patrocinador** possa ser utilizado como publicador.

Portanto para realizarmos essa atividade devemos definir esses campos previamente no **Kernel**!

**Comment by jamilatta** [comment]
Outro ponto **importante** é que o campos de contato são os contatos do periódicos e não do publicador atualmente estamos utilizando os dados de contato do periódico como dados de contato do publicador.

**Comment by joffilyfe** [comment]
> Outro ponto **importante** é que o campos de contato são os contatos do periódicos e não do publicador atualmente estamos utilizando os dados de contato do periódico como dados de contato do publicador.

@jamilatta foi utilizado o campo `contact` para armazenar os dados vindos do [xylose](https://github.com/scieloorg/opac-airflow/blob/master/airflow/dags/sync_isis_to_kernel.py#L139-L144). Temos então que resgatar o histórico mencionado pelo @gustavofonseca e atribuir o nome correto do campo no domínio do kernel.

Dei uma olhada rápida no xylose e nós já temos algo relacionado ao `publisher_name` (qual deles?) [aqui](https://github.com/scieloorg/xylose/blob/master/xylose/scielodocument.py#L1154).

PS: Precisamos replicar a lógica aplicada no `airflow` para a `migração`.

**Comment by jamilatta** [comment]
@joffilyfe 

Acho que fiquei mais confuso com os seus comentário se poder me explicar agradeço!

**Comment by robertatakenaka** [comment]
> Outro ponto **importante** é que o campos de contato são os contatos do periódicos e não do **publicador** atualmente estamos utilizando os dados de contato do periódico como dados de contato do publicador.

Na Title Manager e SciELO Manager "dados do publicador" é o mesmo que "dados da revista", pois na época não havia diferença entre "Publicador" e "Responsável pela Publicação".

**Comment by jamilatta** [comment]
A definição para esse caso ficou da seguinte forma segundo @gustavofonseca: 

<img width="840" alt="Screenshot 2019-12-04 11 31 08" src="https://user-images.githubusercontent.com/373745/70150942-a010af00-1689-11ea-9773-412e58f492c3.png">

**Comment by gustavofonseca** [comment]
Este ticket está amplo demais, portanto vou fechá-lo com a expectativa de que sejam abertos novos tickets mais focados em problemas pontuais.
