### ISSUE TITLE
Reutilizar ids de documentos removidos do kernel

### ISSUE THREAD

**Issue by patymori** [scieloorg/kernel#157]
### Descrição da nova funcionalidade
Eu, como **usuário**, gostaria que **novos documentos fossem criados utilizando ids de documentos removidos do kernel anteriormente**, então **seria possível utilizar estes mesmos ids sem problemas**.

### Critérios de aceitação
- Estas inserções ficariam como novas versões desse documento removido, não a criação de um novo registro de fato no kernel

### Anexos
n/a

### Referências
Ticket para remoção de documentos: #156

**Comment by gustavofonseca** [comment]
Por conta da característica do Kernel de armazenar os registros de maneira imutável, não será possível reciclar os identificadores. A executar a remoção de um registro, o Kernel cria uma nova versão do mesmo indicando que trata-se de uma remoção, mas todas as versões anteriores permanecem acessíveis. Uma vez removido o registro pode receber uma nova versão e constará que ficou removido durante um período e que voltou.

De qualquer maneira, reaproveitar/reciclar IDs é algo perigoso quando falamos de sistemas distribuídos que oferecem garantias fortes de integridade. Algum sistema poderá conter uma chave estrangeira de um registro com a expectativa de que é outro.
