### ISSUE TITLE
Avaliar o endpoint /front

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/kernel#187]
### Descrição 
Em conversa com a equipe acreditamos que o endpoint **/front** é inadequado para o seu retorno, acreditamos que esse endpoint deva se chamar **/metadata**

**Comment by gustavofonseca** [comment]
@jamilatta, 

Inclua aqui, por gentileza, a justificativa para tal crença da equipe.

**Comment by jamilatta** [comment]
@robertatakenaka @joffilyfe @cesarbruschetta @patymori 

Poderiam me ajuda com essa justificativa?

Lembro que fomos unânimes nessa definição!

**Comment by jamilatta** [comment]
Lembrei,  

Durante algumas atualizações do **clea** o Danilo adicionou todos os metadados em uma das funções que esse endpoint está utilizando, o que implica que temos um endpoint que não condiz com seu retorno. 

Nós entendemos que **/front** deve retornar somente os metadados do **front do artigo,** atualmente estamos retornando todos os metadados do artigo. 

@robertatakenaka sugeriu **/metadata**, e a equipe não se opôs, você teria outra sugestão.

**Comment by joffilyfe** [comment]
Atualmente o `/front` retorna apenas o `front` do artigo e o `front-stube` do subarticle caso exista.
