### ISSUE TITLE
Simplificar o schema de metadata de BundleManifest

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/kernel#194]
O schema atual opera no modo _append-only_, incluindo o novo valor ao final sempre que cada campo é atualizado. Este design confere uma capacidade limitada de auditoria e versionamento dos valores, que foi ampliada após a implementação do _snapshot_ junto aos registros de mudança [37d9f348593bb0d3103fbbd1c539d7f225a5362a], e portanto não é mais necessária e deve ser removida.

**Comment by joffilyfe** [comment]
Por não precisarmos mais armazenar todas as mudanças no próprio `bundle`, vejo que ao alteramos o trecho de código em [1] para algo mais simples com uma atribuição, o `kernel` passaria a armazenar os dados da forma de `chave->valor`, exemplo:

```json
{
	"_id" : "0066-782XX",
	"id" : "0066-782XX",
	"created" : "2020-01-08T19:07:35.107992Z",
	"updated" : "2020-01-08T19:08:52.204312Z",
	"items" : [ ],
	"metadata" : {
		"title" : "Título de exemplo"
	}
}
``` 
Em detrimento do modelo antigo, exemplo: 

```json
{
	"_id" : "0066-782XX",
	"id" : "0066-782XX",
	"created" : "2020-01-08T19:07:35.107992Z",
	"updated" : "2020-01-08T19:08:52.204312Z",
	"items" : [ ],
	"metadata" : {
		"title" : [
			[
				"2020-01-08T13:18:48.477479Z",
				"Título de exemplo"
			]
		],
        }
}
```
A responsabilidade em `guardar` as mudanças passa a ser inteiramente da coleção `changes`, o que vocês acham @scieloorg/scielo-brazil-developers?

### Referências

[[1] - set_metadata](https://github.com/scieloorg/kernel/blob/3fac6095d5dfa1020b4f1d8eee16013be3a1895d/documentstore/domain.py#L571-L572)

**Comment by gustavofonseca** [comment]
@joffilyfe, de acordo 👍

**Comment by patymori** [comment]
> 
> A responsabilidade em `guardar` as mudanças passa a ser inteiramente da coleção `changes`, o que vocês acham @scieloorg/scielo-brazil-developers?

Somente para confirmar, a mudança está sendo armazenada no novo campo compactado nos documentos do `changes`, certo? Sendo assim, estou de acordo.

**Comment by joffilyfe** [comment]
> Somente para confirmar, a mudança está sendo armazenada no novo campo compactado nos documentos do `changes`, certo? Sendo assim, estou de acordo.

É isso memso @patymori.

**Comment by robertatakenaka** [comment]
de acordo
