### ISSUE TITLE
[Services] Criar comandos para get, set e remove de bundle de provisional

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/kernel#88]
Deve existir comandos para set, get e remove de um "bundle" de provisioanal PDFs.

O comando set deve receber o identificador do periódico e do fascículo.

O comando get deve receber o identificador do periódico.

O comando remover deve receber o identificador do periódico.

**Comment by gustavofonseca** [comment]
Documentos do tipo _provisional_  não serão mais suportados pelo modelo de publicação do SciELO, invalidando assim este ticket.
